apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: configserver
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: configserver.sbadmin.192.168.64.31.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: configserver
          servicePort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  ports:
  - port: 8888
    name: http
  type: LoadBalancer
  selector:
    app: configserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: gcr.io/fresh-catwalk-240714/config-server:0.0.1-SNAPSHOT
        ports:
          - containerPort: 8888
        env:
          - name: EUREKA_URL
            value: http://eureka.sbadmin.192.168.64.31.nip.io/eureka
